version: '3.8'

services:
  # Servicio de frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: tutoria-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - NODE_ENV=development
    networks:
      - tutoria-network

  # Servicio de backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tutoria-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb
      - ai-service
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tutoria
      - AI_SERVICE_URL=http://ai-service:5001
      - JWT_SECRET=your_jwt_secret_here
      - NODE_ENV=development
      - PORT=5000
    networks:
      - tutoria-network

  # Servicio de IA
  ai-service:
    build:
      context: ./ai-service
      dockerfile: Dockerfile
    container_name: tutoria-ai-service
    ports:
      - "5001:5001"
    volumes:
      - ./ai-service:/app
      - /app/node_modules
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=development
      - PORT=5001
    networks:
      - tutoria-network

  # Base de datos MongoDB
  mongodb:
    image: mongo:5.0
    container_name: tutoria-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=tutoria
    networks:
      - tutoria-network

networks:
  tutoria-network:
    driver: bridge

volumes:
  mongodb-data: